sudo: required
dist: trusty
language: cpp
compiler: 
  - gcc
env:
  global:
    - COMPILER=g++-4.9
    - secure: "DHjLtKNlLjQx3lOqxU6EU8+4zfxosfzINV9wLyYTsiYoOXA8d/8CKWcOo6yvCV7ww8FHrNCcVxiEfdbDadLEG1Wvi6bGW1x1TMTneXYsJqcEIcOouJLkLj8fBvBGkNseMolkXYsISBiCWhG+7XGxBwcSBBTUBrJ//5tbF3NNgrKb/LTps4UJlhvZBww8go9Y9QVyLT+mXJ594blC3LHO1h70HiaP+6AB1Cd5L7cCixUf0lUPDBHq9oGivPq2HUYhmFb0Rlzt+sXK1raw594l1rHxs8GLF0DeBLYF64gqzMSYz9T33ShHeMAizIqnEu5Rcdgu3oPLqvZ+iI7MJdNYnAKIuIv4HsBkNVLAp7T2Ck1tAcHJWt0imcMbtlntWFBXiA2C7ALw+7MMcl9AWI6+EQxXHfjhUwG0P75dzEf5Iq5crXyd3EPxTZbsV/wuo1K9pD7VtVhlo3Bowja4iqrcqEKEJUDoVTKNlHqR9sZ9UQlALO3GMwvn55CVh+zndu9Iok1H5YDGCkfzEbCjeMtAiHJW+n1ue/8ML6tulJFLnEqmUCa9Hn036H/GCIocR0jSMPv9YMx8YhYlseURelJIVwJ5p4EHetRYYNFV2SHf1RwiksaUI7IceUYoMchvbvDAFxXy1RO1gFlmImXfZ4s/v1HsK1BIYQUD89R7wOOx5OU="
addons:
  coverity_scan:
    project:
      name: "LLNL/RAJA"
      description: "Build submitted via Travis CI"
    notification_email: davidbeckingsale@gmail.com
    build_command_prepend: "cd $TRAVIS_BUILD_DIR && cd scripts && ./config-build.py -hc ../host-configs/linux/gnu.cmake && cd build-gnu-release"
    build_command:   "make"
    branch_pattern: coverity-scan
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_install:
  - sudo apt-get update -qq
script:
  - echo "coverity-scan"
  - cat /home/travis/build/LLNL/RAJA/scripts/build-gnu-release/cov-int/scm_log.txt
